### Read all tasks
GET http://localhost:3000/tasks

### Create a single task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "name": "Do the washing"
}

### Read a single task
GET http://localhost:3000/tasks/5950e86356acee1530f30040

### Update a single task
PUT http://localhost:3000/tasks/5950e86356acee1530f30040
Content-Type: application/json

{
  "name": "I updated the name! Woohoo!"
}

### Delete a single task
DELETE http://localhost:3000/tasks/5950e77356acee1530f3003f